# Generated by Django 5.0.6 on 2024-05-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('cliente', models.TextField(max_length=255)),
            ],
        ),
    ]
