# Generated by Django 5.0.6 on 2024-05-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_da_venda', models.IntegerField()),
                ('cliente', models.TextField(max_length=255)),
                ('produto', models.TextField(max_length=255)),
                ('quantidade', models.TextField(max_length=255)),
                ('valor_de_venda', models.TextField(max_length=255)),
                ('taxas', models.TextField(max_length=255)),
                ('valor_liquido', models.TextField(max_length=255)),
                ('prazo', models.TextField(max_length=255)),
                ('canal_de_venda', models.TextField(max_length=255)),
                ('codigo_de_rastreio', models.TextField(max_length=255)),
            ],
        ),
    ]
