# Generated by Django 5.0.6 on 2024-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_da_venda',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxas',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_de_venda',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_liquido',
            field=models.IntegerField(max_length=255),
        ),
    ]
