# Generated by Django 5.0.6 on 2024-05-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pedidos',
            new_name='Pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='numero',
            new_name='pedido',
        ),
    ]
