# Generated by Django 5.0.6 on 2024-06-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pedido_data_da_venda_alter_pedido_prazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimentacao', models.CharField(choices=[('1', 'Receita'), ('2', 'Custo'), ('3', 'Descpesa')], default='1', max_length=3)),
                ('descricao_movimentacao', models.TextField(max_length=255)),
                ('valor_movimentacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_movimentacao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='canal_de_venda',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_de_rastreio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_de_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
